apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: transcriber-backend
spec:
  type: LoadBalancer
  selector:
    app: transcriber-backend
  ports:
  - protocol: TCP
    port: 8000       # Exposed service port
    targetPort: 8000 # Container port
